export const POSTERS = {
	en: [
		{
			eyebrow: "Automatic photo finding",
			a: "It finds the photos.",
			b: "You tap share.",
			sub: "Recapd scans your camera roll for the hours of the event and picks every shot for you.",
			callouts: [
				["zap", "Found automatically", "r", 0.68],
				["clock", "Only from the event hours", "l", 0.47],
			],
		},
		{
			eyebrow: "No app. No account.",
			a: "They scan.",
			b: "They’re in.",
			sub: "Guests join from the browser with a first name. Nothing to download, no password.",
			callouts: [
				["globe", "Works in the browser", "r", 0.27],
				["check", "No sign-up wall", "l", 0.38],
			],
		},
		{
			eyebrow: "One shared album",
			a: "Everyone’s photos.",
			b: "One album.",
			sub: "Every guest’s camera roll in one live album, from the first dance to the last song.",
			callouts: [
				["users", "24 cameras", "l", 0.56],
				["zap", "Appears instantly", "r", 0.78],
			],
		},
		{
			eyebrow: "Original quality",
			a: "Full resolution.",
			b: "Not chat-app mush.",
			sub: "Photos and videos arrive exactly as they were shot. Zoom all the way in.",
			callouts: [
				["maximize", "Pinch to zoom", "l", 0.42],
				["image", "12 MP original", "r", 0.66],
			],
		},
		{
			eyebrow: "Background uploads",
			a: "Lock your phone.",
			b: "It keeps going.",
			sub: "Share hundreds of photos at once, put the phone away and get back to the party.",
			callouts: [
				["lock", "Screen locked", "r", 0.5],
				["upload", "Hundreds at once", "l", 0.72],
			],
		},
		{
			eyebrow: "New: event info",
			a: "Where, when,",
			b: "what to wear.",
			sub: "Location, dress code, schedule and a countdown. Add it to your calendar in one tap.",
			callouts: [
				["clock", "Live countdown", "r", 0.2],
				["list", "Schedule", "r", 0.72],
			],
		},
		{
			eyebrow: "New: built-in camera",
			a: "Shoot it here.",
			b: "It’s in the album.",
			sub: "Snap with the Recapd camera and every shot goes straight to the event album.",
			callouts: [
				["camera", "Photo and video", "l", 0.3],
				["check", "Straight to the album", "r", 0.62],
			],
		},
		{
			eyebrow: "Private by design",
			a: "Save the whole night.",
			b: "Then it’s gone.",
			sub: "Download every photo in full resolution. No feed, no followers. Gone after 14 days.",
			callouts: [
				["shield", "Invite only", "r", 0.2],
				["download", "Whole album, one tap", "l", 0.49],
			],
		},
	],
	nb: [
		{
			eyebrow: "Finner bildene automatisk",
			a: "Den finner bildene.",
			b: "Du trykker del.",
			sub: "Recapd leter gjennom kamerarullen etter bilder fra arrangementet og velger dem ut for deg.",
			callouts: [
				["zap", "Funnet automatisk", "r", 0.68],
				["clock", "Bare fra tidsrommet", "l", 0.47],
			],
		},
		{
			eyebrow: "Ingen app. Ingen konto.",
			a: "De skanner.",
			b: "De er med.",
			sub: "Gjestene blir med fra nettleseren med bare fornavn. Ingenting å laste ned, ikke noe passord.",
			callouts: [
				["globe", "Virker i nettleseren", "r", 0.27],
				["check", "Ingen registrering", "l", 0.38],
			],
		},
		{
			eyebrow: "Ett delt album",
			a: "Alles bilder.",
			b: "Ett album.",
			sub: "Alle gjestenes kamerarull i ett levende album, fra første dans til siste sang.",
			callouts: [
				["users", "24 kameraer", "l", 0.56],
				["zap", "Dukker opp med en gang", "r", 0.78],
			],
		},
		{
			eyebrow: "Original kvalitet",
			a: "Full oppløsning.",
			b: "Ikke chat-grøt.",
			sub: "Bilder og video kommer frem akkurat slik de ble tatt. Zoom helt inn.",
			callouts: [
				["maximize", "Knip for å zoome", "l", 0.42],
				["image", "12 MP original", "r", 0.66],
			],
		},
		{
			eyebrow: "Laster opp i bakgrunnen",
			a: "Lås telefonen.",
			b: "Den fortsetter.",
			sub: "Del hundrevis av bilder på en gang, legg bort telefonen og bli med på festen igjen.",
			callouts: [
				["lock", "Skjermen er låst", "r", 0.5],
				["upload", "Hundrevis på en gang", "l", 0.72],
			],
		},
		{
			eyebrow: "Nytt: info om festen",
			a: "Hvor, når",
			b: "og hva du har på.",
			sub: "Sted, antrekk, program og nedtelling. Legg det i kalenderen med ett trykk.",
			callouts: [
				["clock", "Nedtelling", "r", 0.2],
				["list", "Program", "r", 0.72],
			],
		},
		{
			eyebrow: "Nytt: innebygd kamera",
			a: "Ta bildet her.",
			b: "Det er i albumet.",
			sub: "Knips med Recapd-kameraet, så havner hvert bilde rett i albumet.",
			callouts: [
				["camera", "Bilde og video", "l", 0.3],
				["check", "Rett i albumet", "r", 0.62],
			],
		},
		{
			eyebrow: "Privat fra start",
			a: "Lagre hele kvelden.",
			b: "Så er den borte.",
			sub: "Last ned alle bildene i full oppløsning. Ingen feed, ingen følgere. Borte etter 14 dager.",
			callouts: [
				["shield", "Bare for inviterte", "r", 0.2],
				["download", "Hele albumet, ett trykk", "l", 0.49],
			],
		},
	],
};

export const FEATURE = {
	en: {
		a: "It finds the photos.",
		b: "You tap share.",
		sub: "The shared album for weddings, birthdays and every party. Guests join by QR, no sign-up.",
		chips: ["Finds your photos", "Full resolution", "Private"],
	},
	nb: {
		a: "Den finner bildene.",
		b: "Du trykker del.",
		sub: "Det delte albumet for bryllup, bursdager og alle fester. Gjestene blir med via QR, uten konto.",
		chips: ["Finner bildene", "Full oppløsning", "Privat"],
	},
};

export const UI = {
	en: {
		tabHome: "Home",
		tabEvents: "My Events",
		tabSettings: "Settings",
		addPhotos: "Add your photos",
		found: (n) => `We found ${n} photos from tonight`,
		window: "Sat 19:00 to 02:00 · from your camera roll",
		selected: (n) => `${n} selected`,
		already: "2 videos included",
		all: "All",
		none: "None",
		shareN: (p, v) => `Share ${p} photos & ${v} videos`,
		bgHint: "Uploads keep going with the phone locked.",
		invite: "Invite guests",
		scanToJoin: "Scan to join",
		noApp: "No app needed. Opens in any browser.",
		shareLink: "Share the link",
		joining: "Joining now",
		tonight: (n) => `${n} tonight`,
		justNow: "just now",
		minAgo: (n) => `${n} min ago`,
		browser: "Browser",
		eventAlbum: "Event album",
		liveNow: "Live now",
		adding: (n) => `${n} guests adding photos`,
		photos: "Photos",
		videos: "Videos",
		guests: "Guests",
		feed: "The feed",
		newest: "Newest first",
		original: "Original",
		download: "Download",
		uploading: (a, b) => `Uploading ${a} of ${b}`,
		locked: "Even with the screen locked",
		yourPhotos: "Your photos",
		uploaded: "Uploaded",
		startsIn: "Starts in",
		days: "days",
		hrs: "hrs",
		min: "min",
		location: "Location",
		dress: "Dress code",
		schedule: "Schedule",
		addCal: "Add to calendar",
		dressValue: "Costumes. The scarier the better.",
		locValue: "Thorvald Meyers gate 12, Oslo",
		sched: [
			["19:00", "Doors open"],
			["20:30", "Costume contest"],
			["22:00", "Pumpkin carving"],
			["23:30", "Dance floor"],
		],
		camAdding: "Adding to Festival weekend",
		camAdded: "Added to the album",
		photo: "Photo",
		video: "Video",
		saveAll: "Download all",
		saving: (a, b) => `${a} of ${b} · full resolution`,
		toRoll: "Saving to your camera roll",
		deletes: "Deletes in 11 days",
		privacy: "Private album",
		p1: "Only people with the invite",
		p2: "No public feed, no followers",
		p3: "Deleted 14 days after the event",
	},
	nb: {
		tabHome: "Hjem",
		tabEvents: "Mine eventer",
		tabSettings: "Innstillinger",
		addPhotos: "Legg til bildene dine",
		found: (n) => `Vi fant ${n} bilder fra i kveld`,
		window: "Lør 19:00 til 02:00 · fra kamerarullen",
		selected: (n) => `${n} valgt`,
		already: "2 videoer med",
		all: "Alle",
		none: "Ingen",
		shareN: (p, v) => `Del ${p} bilder og ${v} videoer`,
		bgHint: "Opplastingen fortsetter med låst telefon.",
		invite: "Inviter gjester",
		scanToJoin: "Skann for å bli med",
		noApp: "Ingen app nødvendig. Åpnes i nettleseren.",
		shareLink: "Del lenken",
		joining: "Blir med nå",
		tonight: (n) => `${n} i kveld`,
		justNow: "akkurat nå",
		minAgo: (n) => `${n} min siden`,
		browser: "Nettleser",
		eventAlbum: "Album",
		liveNow: "Pågår nå",
		adding: (n) => `${n} gjester legger til bilder`,
		photos: "Bilder",
		videos: "Videoer",
		guests: "Gjester",
		feed: "Feeden",
		newest: "Nyeste først",
		original: "Original",
		download: "Last ned",
		uploading: (a, b) => `Laster opp ${a} av ${b}`,
		locked: "Også med låst skjerm",
		yourPhotos: "Bildene dine",
		uploaded: "Lastet opp",
		startsIn: "Starter om",
		days: "dager",
		hrs: "timer",
		min: "min",
		location: "Sted",
		dress: "Antrekk",
		schedule: "Program",
		addCal: "Legg i kalenderen",
		dressValue: "Kostyme. Jo skumlere, jo bedre.",
		locValue: "Thorvald Meyers gate 12, Oslo",
		sched: [
			["19:00", "Dørene åpner"],
			["20:30", "Kostymekonkurranse"],
			["22:00", "Gresskarskjæring"],
			["23:30", "Dansegulvet åpner"],
		],
		camAdding: "Legges i Festivalhelg",
		camAdded: "Lagt i albumet",
		photo: "Bilde",
		video: "Video",
		saveAll: "Last ned alle",
		saving: (a, b) => `${a} av ${b} · full oppløsning`,
		toRoll: "Lagres i kamerarullen",
		deletes: "Slettes om 11 dager",
		privacy: "Privat album",
		p1: "Bare de som er invitert",
		p2: "Ingen offentlig feed, ingen følgere",
		p3: "Slettes 14 dager etter festen",
	},
};

export const NAMES = {
	en: {
		mia30: "Mia’s 30th",
		halloween: "Halloween at Mia’s",
		wedding: "Sarah & James",
		weddingSub: "Grand Hotel · Oslo",
		weddingTitle: "The Wedding",
		grad: "Class of 2026",
		xmas: "Office Christmas party",
		nye: "New Year’s Eve",
		festival: "Festival weekend",
	},
	nb: {
		mia30: "Mia 30 år",
		halloween: "Halloween hos Mia",
		wedding: "Sarah & James",
		weddingSub: "Grand Hotel · Oslo",
		weddingTitle: "Bryllupet",
		grad: "Avslutningsfest",
		xmas: "Julebord",
		nye: "Nyttårsaften",
		festival: "Festivalhelg",
	},
};
